name: RandomItemChallengeVSJuggernaut
author: Lanfix
version: '${project.version}'
main: fr.lanfix.randomitemchallengevsjuggernaut.RandomItemChallengeVSJuggernaut
api-version: '1.20'
commands:
  ricvsjuggernaut:
    description: Control the Random Item Challenge VS Juggernaut Game
    permission: randomitemchallengevsjuggernaut.admin
    usage: /ricvsjuggernaut <start/stop/juggernauts/survivors>